media:
  input: files/media    
  output: public/media  

content: 
   - name: blogs
     label: Blogs
     path: src/content/blogs
     type: collection
     fields: 
      - {name: "title", label: "Title", type: "string"}
      - {name: "description", label: "Description", type: "string"}
      - {name: "image", label: "Image", type: "image"}
      - {name: "imageAlt", label: "ImageAlt", type: "string"}
      - {name: "href", label: "Href", type: "string"}
     